### ISSUE TITLE
E2EE Key

### ISSUE THREAD

**Issue by samerkh84** [raj457036/copycat_clipboard#13]
Hello, please explain a method supported by the software to generate the encryption key

**Comment by raj457036** [comment]
Explain? if you want to know how the encryption is done! you can checkout the encryption code [here](https://github.com/raj457036/copycat_base/blob/main/lib/data/services/encryption.dart)

Let me know if this is clear.

**Comment by samerkh84** [comment]
When I click on the corresponding option, it asks me for the e2ee file

![Screenshot 2024-09-14 163649](https://github.com/user-attachments/assets/c5278272-7b04-4352-b552-983974a49e3e)

**Comment by raj457036** [comment]
If its asking for e2ee file it means you have already minted it for your account in one of your devices please export it from that device and import it other devices
