### ISSUE TITLE
Are clips encrypted when stored on Google Drive?

### ISSUE THREAD

**Issue by gggirlgeek** [raj457036/copycat_clipboard#16]
Hi, and thanks for the great looking app. It might be just what I'm looking for.

Silly question: Since Google indexes everything it stores, are clips encrypted at rest on Google Drive when I use the E2EE option? Encryption is very confusing and it's hard to keep track of what E2EE is as apposed to other protocols. It seems like there's always a "gottcha" with each of them.

If not, I would prefer to use another storage provider to synch my clipboard. Inevitably a password or credit card # will get copied, so I don't want to have to worry about it. (This is why I am not using clipboard synching apps currently.) I am thinking that your app might make a great note taker. We shall see. :-)

**Comment by raj457036** [comment]
Hey,

Just to clarify, CopyCat encrypts text-based ( transit and at rest ) data to ensure security. However, encrypting and decrypting large files at rest can be quite time-consuming, so only text data is encrypted.

As for your question about Google Drive indexing your data—while it’s true that Google indexes most content on your drive, this does not apply to the AppDataFolder. CopyCat uses this special hidden folder in your personal Google Drive to temporarily store your files. These files are automatically deleted after a certain time (depending on your plan) if the clip isn't part of any collection.

According to Google's documentation:

"The application data folder is a special hidden folder that your app can use to store application-specific data, such as configuration files. This folder is only accessible by your application, and its contents are hidden from both the user and other Drive apps." You can find more information here: [Google Drive AppData Documentation](https://developers.google.com/drive/api/guides/appdata).

As for adding support for another storage provider, it's definitely on the roadmap, but it's not a priority at the moment as we’re focusing on other aspects of the app for now.

Let me know if you need any clarification.
