### ISSUE TITLE
How do I enable the 'Encrypt Clipboard' setting?

### ISSUE THREAD

**Issue by foxdodo** [raj457036/copycat_clipboard#7]
The 'Encrypt Clipboard' option was enabled, but after restarting the app, it reverted to its disabled state.
I've tested it on both desktop and iOS.

**Comment by raj457036** [comment]
Can you please add a video to explain the issue. i tried to reporduce it but no success.

**Comment by raj457036** [comment]
Could you please add a video to explain the issue? I tried to reproduce it but was unsuccessful.

**Comment by raj457036** [comment]
Thanks for the video. i was able to reproduce it in free plan. the free plan currently resets the encrypt switch in setting. will be fixed in 0.1.23. 

Again thanks again for letting me know about it.
